calculate_delay:
  outputs:
    dev:
      dbname: "{{ env_var('DBT_DBNAME') }}"
      host: "{{ env_var('DBT_HOST') }}"
      pass: "{{ env_var('DBT_PASSWORD') }}"
      port: 5432
      schema: 'public'
      threads: 1
      type: postgres
      user: "{{ env_var('DBT_USER') }}"
  target: dev